common:
  csv_columns:
    - 'title'
    - 'definition'

create_pinecone_index:
  index_name: 'umls-cui-hybrid-semantic-search'
  dimension: 768
  metric: 'dotproduct'
  pod_type: 'p1'
  namespaces:
    - 'title'
    - 'definition'

embed:
  csv_columns: ${common.csv_columns}
  hybrid:
    dense:
      library: 'sentence_transformers'
      function: 'SentenceTransformer'
      model_name: 'pritamdeka/PubMedBERT-mnli-snli-scinli-scitail-mednli-stsb'
      batch_size: 3000
      normalize: True
      device: 'cpu'
    sparse:
      tokenizer:
        library: 'transformers'
        function: 'AutoTokenizer'
        model_name: 'naver/splade-cocondenser-ensembledistil'
      library: 'transformers'
      function: 'AutoModelForMaskedLM'
      model_name: 'naver/splade-cocondenser-ensembledistil'
      batch_size: 100
      normalize: True
      device: 'cpu'

upsert:
  filepath_raw: 'C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-search/brics_search/brics_dd/data/dataElementExport_published-CDEs_2023-05-31.csv'
  filepath_processed: 'C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-search/brics_search/brics_dd/data/dataElementExport_published-CDEs_2023-05-31_processed.pkl'
  application_type: hybrid semantic search
  embed:
    csv_columns: ${common.csv_columns}
  metadata:
    tokenize_columns: 
      tokenize: True
      include_tokenized: True 
      columns: ${common.csv_columns}
      tokenizer:
        library: 'transformers'
        function: 'AutoTokenizer'
        model_name: 'transfo-xl-wt103'
    include_columns: # DATA dICTIONARY CSV COLUMNS TO INCLUDE IN PINECONE INDEX
      - 'variable_name'
      - 'title'
      - 'definition'
      - 'data_element_concept_identifiers'
      - 'data_element_concept_names'
      - 'permissible_values'
      - 'permissible_value_descriptions'
      - 'preferred_question_text'
      - 'datatype'
      - 'input_restriction'
      - 'guidelines_instructions'
      - 'notes'
      - 'population_all'
      - 'creation_date'
      - 'submitting_contact_name'

query:
  application_type: hybrid semantic search
  namespace: ${common.csv_columns}
  top_k: 20
  alpha: 1.0
  df_display:
    cols_order: ${upsert.metadata.csv_columns}


