studyinfo_loader:
  api:
    endpoint_url: "https://fitbir.nih.gov/gateway//repository-api/study"
    login_url: "https://fitbir.nih.gov/gateway/authentication/user/login"

  storage:
    storage_path_root: "./storage/data_repository/"
    filename: "studies.csv"

  authentication:
    prompt_username: true
    prompt_password: true
