defaults:
  - _self_
  - loaders: studyinfo_loader
  - preprocessors: studyinfo_preprocessor
  - document_creators: studyinfo_document
  - node_parsers: studyinfo_nodes
  - index_managers:
    - studyinfo_vectorstore
  - query_engines: studyinfo_query_engine
  - evaluators: studyinfo_question_dataset

settings:
  log_level: 'info'

