studyinfo_summary_index:
  index_id: 'FITBIR-Data-Repository_DocumentSummaryIndex'
  filepath_input: 'C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/examples/data_repository/storage/studies.csv'
  storage_context:
    storage_path_root: 'C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/examples/data_repository/storage/'
    storage_paths_indices:
  summary: "FITBIR Data Repository Study Information"
  service_context:
    llm:
      llm_service: "OpenAI"  # or "AnotherService"
      llm_kwargs:
        model_name: "gpt-3.5-turbo"
        temperature: 0.1
      context_window: 4096
    chunk_size: 1024
  response_synthesizer:
    response_mode: "tree_summarize"
    use_async: True
