indices:
  index:
    index_id: fitbir_data_dictionary
    filepath_input: C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/brics_tools/brics_dd/storage/fitbir/FITBIR_DD_published_2023-07-21.csv
    summary: 'FITBIR Data Dictionary Embeddings:'
    collections:
      embed:
        id_column: variable name
        columns:
        - title
        - definition
        model_name: pritamdeka/PubMedBERT-mnli-snli-scinli-scitail-mednli-stsb
        model_kwargs:
          batch_size: 500
          device: cpu
          normalize_embeddings: true
      names:
      - title
      - definition
      distance_metric:
        hnsw:space: cosine
      metadata_columns:
      - variable name
      - title
      - element type
      - definition
      - short description
      - datatype
      - input restriction
      - minimum value
      - maximum value
      - data element concept identifiers
      - data element concept names
      - permissible values
      - permissible value descriptions
      - permissible value concept identifiers
      - permissible value concept names
      - unit of measure
      - preferred question text
      - creation date
      - last change date
      storage_path_root: C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/brics_tools/brics_dd/storage/fitbir
      storage_paths_indices:
        definition: C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/brics_tools/brics_dd/storage/fitbir/definition
        title: C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/brics_tools/brics_dd/storage/fitbir/title
semantic_search:
  data_dictionary:
    filepath_input: C:/Users/armengolkm/Documents/BRICS/Data_Elements_Form_Structures/CNTR
      NTRR (NTI) data dictionary/Crossmap/CNTR_DEs.csv
    directory_output: C:/Users/armengolkm/Documents/BRICS/Data_Elements_Form_Structures/CNTR
      NTRR (NTI) data dictionary/Crossmap/
    filepath_curation: null
    embed:
      id_column: variable name
      columns:
      - title
      - definition
    metadata_columns:
    - variable name
    - title
    - definition
    - permissible values
    - permissible value descriptions
    - preferred question text
  query:
    storage_path_root: C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/brics_tools/brics_dd/storage/fitbir
    storage_paths_indices: null
    queries:
      title_title:
      - title
      - title
      definition_definition:
      - definition
      - definition
    similarity_top_k: 10
    rerank:
      cross_encoder:
        model_name: cross-encoder/stsb-distilroberta-base
        top_n: 10
    include:
    - documents
    - metadatas
    - ids
    where: null
    where_document: null
