data_dictionary:
  filepath_input:  'C:/Users/armengolkm/Documents/BRICS/Data_Elements_Form_Structures/CNTR NTRR (NTI) data dictionary/Crossmap/CNTR_DEs.csv'
  directory_output: 'C:/Users/armengolkm/Documents/BRICS/Data_Elements_Form_Structures/CNTR NTRR (NTI) data dictionary/Crossmap/'
  filepath_curation: 
  embed:
    id_column: 'variable name'
    columns:
    - 'title'
    - 'definition'
  metadata_columns: 
  - 'variable name'
  - 'title'
  - 'definition'
  - 'permissible values'
  - 'permissible value descriptions'
  - 'preferred question text'
 

query:
  storage_path_root: 'C:/Users/armengolkm/Desktop/VS_Code_Projects/BRICS/brics-tools/brics_tools/brics_dd/storage/fitbir'
  storage_paths_indices:
  queries:
    title_title: [title, title]
    definition_definition: [definition, definition]
  similarity_top_k: 10
  rerank:
    cross_encoder:
      model_name: "cross-encoder/stsb-distilroberta-base"
      top_n: 10
  include: ['documents','metadatas','ids']
  where:
  where_document:


  

